version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:3000'
    deploy:
      resources:
          limits:
            cpus: "0.5"
            memory: 512m
    environment:
      SERVER_PORT: 3000
    volumes:
      - ./backend/src:/app/src
