version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      SERVER_PORT: 3000
    volumes:
      - ./backend/src:/app/src
